"""Add name and profile_pic to User model

Revision ID: 5526272cd55e
Revises: a9b3b0dd28dc
Create Date: 2025-04-27 16:17:27.389152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5526272cd55e'
down_revision = 'a9b3b0dd28dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('profile_pic', sa.String(length=200), nullable=True))
        batch_op.drop_index('ix_user_google_id')
        batch_op.create_unique_constraint(None, ['google_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index('ix_user_google_id', ['google_id'], unique=1)
        batch_op.drop_column('profile_pic')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
